volumes_root: Volumes
catalog_name: marvelous_dev_ops
schema_name: video_games_sales

data_path: data/data.csv

parameters:
  learning_rate: 0.01

ab_test:
  learning_rate_a: 0.01
  learning_rate_b: 0.02

num_features:
  - Rank
  - Year
  - NA_Sales
  - JP_Sales
  - Other_Sales
  - Global_Sales

cat_features:
  - Name
  - Platform
  - Genre
  - Publisher

target: EU_Sales
